name: NX°

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Friendly message - Start
        run: echo "👋 Welcome! This workflow is a placeholder and does not perform any build steps."
      - name: Friendly message - End
        run: echo "✅ All done! No build actions were performed. Have a great day!"
